
title: My Resume
url: 'https://chadtracy.github.io/'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Chad Tracy  ## put your name
title: 'Programmer &amp; Analyst'  ## your title
location: Louisville, KY


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/chad-tracy-239349a4/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
